sudo: required
services:
  - docker

before_install: 
  - docker build -t hfcdevops/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true hfcdevops/react-test npm test -- --coverage

after_success:
  docker build -t hfcdevops/multi-client ./client 
  docker build -t hfcdevops/multi-nginx ./nginx
  docker build -t hfcdevops/multi-server ./server 
  docker build -t hfcdevops/multi-worker ./worker 

